# -*- coding: utf-8 -*-
"""ML Agent - Conversation Awareness

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TuNtyC5GHcnEnTM6vJG2VLeptQt5oGeM
"""

# ============================================================
# PART 1: TRAIN ML MODEL TO RETURN ENGAGEMENT SCORE + STATUS
# ============================================================


# 2. Imports
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


# 3. Load dataset
df = pd.read_csv("sangha_conversations_no_score_500.csv")

print(df.shape)
df.head()

# 4. Create engagement score labels

def create_engagement_score(row):
    msg_a = row["message_count_a"]
    msg_b = row["message_count_b"]
    total_msgs = msg_a + msg_b

    if total_msgs == 0:
        return 0

    balance = min(msg_a, msg_b) / max(msg_a, msg_b)
    message_depth = min(total_msgs / 40, 1)
    length_quality = min(row["avg_message_length"] / 40, 1)
    speed_quality = max(0, 1 - row["avg_response_times_minutes"] / 1500)
    recency = max(0, 1 - row["last_response_hours_ago"] / 72)
    duration = min(row["conversation_days"] / 7, 1)

    score = (
        balance * 25 +
        message_depth * 20 +
        length_quality * 15 +
        speed_quality * 15 +
        recency * 15 +
        duration * 10
    )

    return round(score, 2)


df["engagement_score"] = df.apply(create_engagement_score, axis=1)

df[["conversation_id", "engagement_score"]].head()

# 5. Feature engineering

df["total_messages"] = df["message_count_a"] + df["message_count_b"]

df["message_gap"] = abs(
    df["message_count_a"] - df["message_count_b"]
)

df["message_balance_ratio"] = df.apply(
    lambda row: min(row["message_count_a"], row["message_count_b"]) / max(row["message_count_a"], row["message_count_b"])
    if max(row["message_count_a"], row["message_count_b"]) > 0
    else 0,
    axis=1
)

df.head()

# 6. Define features and target

TEXT_COL = "conversation_text"

numeric_features = [
    "avg_response_times_minutes",
    "message_count_a",
    "message_count_b",
    "conversation_days",
    "avg_message_length",
    "last_response_hours_ago",
    "total_messages",
    "message_gap",
    "message_balance_ratio"
]

X = df[[TEXT_COL] + numeric_features]
y = df["engagement_score"]

# 7. Build ML pipeline

preprocessor = ColumnTransformer(
    transformers=[
        (
            "text",
            TfidfVectorizer(
                max_features=1500,
                ngram_range=(1, 2),
                stop_words="english"
            ),
            TEXT_COL
        ),
        (
            "num",
            StandardScaler(),
            numeric_features
        )
    ]
)

model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regressor", RandomForestRegressor(
            n_estimators=300,
            max_depth=10,
            min_samples_split=4,
            random_state=42
        ))
    ]
)

# 8. Train/test split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model.fit(X_train, y_train)

print("Model trained.")

# 9. Evaluate model

predictions = model.predict(X_test)

mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("MODEL PERFORMANCE")
print("------------------")
print("MAE:", round(mae, 2))
print("MSE:", round(mse, 2))
print("R2 :", round(r2, 2))

# 10. Classification rules

def classify_conversation(row, score):
    msg_a = row["message_count_a"]
    msg_b = row["message_count_b"]

    if row["last_response_hours_ago"] >= 24:
        return "stalled"

    imbalance_ratio = max(msg_a, msg_b) / max(1, min(msg_a, msg_b))

    if imbalance_ratio >= 3:
        return "one_sided"

    if (
        row["avg_message_length"] < 10 and
        row["avg_response_times_minutes"] > 1000
    ):
        return "shallow"

    if score >= 90 and row["conversation_days"] >= 5:
        return "ready_for_event"

    if (65 <= score < 90) or (score >= 90 and row["conversation_days"] < 5):
        return "healthy"

    return "shallow"

# 11. Analyze any raw conversation

def analyze_raw_conversation(
    conversation_text,
    avg_response_times_minutes,
    message_count_a,
    message_count_b,
    conversation_days,
    avg_message_length,
    last_response_hours_ago
):
    total_messages = message_count_a + message_count_b
    message_gap = abs(message_count_a - message_count_b)

    message_balance_ratio = (
        min(message_count_a, message_count_b) / max(message_count_a, message_count_b)
        if max(message_count_a, message_count_b) > 0
        else 0
    )

    raw_row = {
        "conversation_text": conversation_text,
        "avg_response_times_minutes": avg_response_times_minutes,
        "message_count_a": message_count_a,
        "message_count_b": message_count_b,
        "conversation_days": conversation_days,
        "avg_message_length": avg_message_length,
        "last_response_hours_ago": last_response_hours_ago,
        "total_messages": total_messages,
        "message_gap": message_gap,
        "message_balance_ratio": message_balance_ratio
    }

    row_df = pd.DataFrame([raw_row])

    score = model.predict(row_df[[TEXT_COL] + numeric_features])[0]
    score = round(float(score), 2)

    status = classify_conversation(raw_row, score)

    return {
        "engagement_score": score,
        "status": status
    }

# 12. Test with any raw conversation

conversation = """
A: Hey! Are you going to the meditation event this weekend?
B: I was thinking about it! Have you gone before?
A: Yes, it’s really peaceful. I think you’d like it.
B: That sounds sweet actually.
A: Want to go together?
B: Maybe yes :)
"""

result = analyze_raw_conversation(
    conversation_text=conversation,
    avg_response_times_minutes=45,
    message_count_a=3,
    message_count_b=3,
    conversation_days=6,
    avg_message_length=12,
    last_response_hours_ago=2
)

result

# 13. Save model

joblib.dump(model, "sangha_engagement_score_model.pkl")

print("Model saved.")

# ============================================================
# PART 2: USE profile.csv + GROQ TO GENERATE RECOMMENDATION
# Trigger this on button click later
# ============================================================

import pandas as pd
import os
from getpass import getpass

from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage

# ============================================================
# 1. LOAD PROFILES
# ============================================================

profiles_df = pd.read_csv("profiles.csv")

print(profiles_df.shape)
profiles_df.head()

# ============================================================
# 2. SET GROQ API KEY
# ============================================================

os.environ["GROQ_API_KEY"] = os.getenv("GROQ_API_KEY")

# ============================================================
# 3. INITIALIZE GROQ LLM
# ============================================================

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.7
)

# ============================================================
# 4. PROFILE LOOKUP
# Adjust user_id column name if your profile.csv uses a different one
# ============================================================

def get_user_profile(user_id, profiles_df):
    user_row = profiles_df[profiles_df["user_id"] == user_id]

    if user_row.empty:
        return "No profile available."

    profile = user_row.iloc[0].to_dict()

    profile_text = "\n".join([
        f"{key}: {value}"
        for key, value in profile.items()
        if pd.notna(value)
    ])

    return profile_text

# ============================================================
# 5. STATUS STRATEGY
# ============================================================

def create_prompt_strategy(status):
    if status == "ready_for_event":
        return "Gently suggest moving toward an event invite."

    if status == "healthy":
        return "Keep the conversation warm and flowing."

    if status == "one_sided":
        return "Change the tone, make it more interesting"

    if status == "shallow":
        return "Ask a simple but more meaningful question."

    if status == "stalled":
        return "Send a soft, low-pressure re-opening message."

    return "Continue naturally."

# ============================================================
# 6. GROQ RECOMMENDATION GENERATOR
# ============================================================

def generate_recommendation_with_profiles(
    conversation_text,
    engagement_score,
    status,
    sender_profile,
    receiver_profile
):
    strategy = create_prompt_strategy(status)

    prompt = f"""
You are helping a user continue a conversation on Sangha, a spiritual community app.

Conversation:
{conversation_text}

Engagement Score:
{engagement_score}

Conversation Status:
{status}

Strategy:
{strategy}

Sender Profile:
{sender_profile}

Receiver Profile:
{receiver_profile}

Task:
Write a recommendation and one suggested message the sender can send.

Use the profiles to make the message feel relevant, but do not be creepy.
Do not directly mention private profile details unless they naturally fit.
Do not over-personalize.

Return output in this exact format:

Recommendation:
...

Suggested Message:
...

Rules:
- Warm
- Human
- Casual
- Not salesy
- Not intense
- Make it short and action oriented
"""

    response = llm.invoke([
        SystemMessage(
            content="You write emotionally intelligent conversation recommendations for a spiritual community app."
        ),
        HumanMessage(content=prompt)
    ])

    return response.content

# ============================================================
# 7. BUTTON-CLICK FUNCTION
# This is the function your app/backend should call
# ============================================================

def on_recommendation_button_click(
    conversation_text,
    avg_response_times_minutes,
    message_count_a,
    message_count_b,
    conversation_days,
    avg_message_length,
    last_response_hours_ago,
    sender_user_id,
    receiver_user_id
):
    # Step 1: Use ML model from Part 1
    result = analyze_raw_conversation(
        conversation_text=conversation_text,
        avg_response_times_minutes=avg_response_times_minutes,
        message_count_a=message_count_a,
        message_count_b=message_count_b,
        conversation_days=conversation_days,
        avg_message_length=avg_message_length,
        last_response_hours_ago=last_response_hours_ago
    )

    engagement_score = result["engagement_score"]
    status = result["status"]

    # Step 2: Get profiles
    sender_profile = get_user_profile(sender_user_id, profiles_df)
    receiver_profile = get_user_profile(receiver_user_id, profiles_df)

    # Step 3: Generate Groq recommendation
    llm_output = generate_recommendation_with_profiles(
        conversation_text=conversation_text,
        engagement_score=engagement_score,
        status=status,
        sender_profile=sender_profile,
        receiver_profile=receiver_profile
    )

    return {
        "engagement_score": engagement_score,
        "status": status,
        "llm_recommendation": llm_output
    }

# ============================================================
# 8. TEST BUTTON CLICK
# ============================================================

conversation = """
A: Hey! Are you going to the meditation event this weekend?
A: Would you like to join me for the event?
A: Maybe you can tell me something about yourself first?
B: Hey, ya sure, I like meditation
A: Ok cool I like meditation also
A: So the event is like a meditation session.
B: That sounds sweet actually.
A: Want to go together?
B: Maybe yes :)
"""

result = on_recommendation_button_click(
    conversation_text=conversation,
    avg_response_times_minutes=45,
    message_count_a=12,
    message_count_b=3,
    conversation_days=6,
    avg_message_length=4,
    last_response_hours_ago=12,
    sender_user_id="user_001",
    receiver_user_id="user_002"
)

print(result["engagement_score"])
print(result["status"])
print(result["llm_recommendation"])

